---
title: Sc2mapster Github
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  editor_tutorials:
    output: true
theme: jekyll-theme-primer
repository: Sc2mapster/sc2mapster.github.io
defaults:
  - scope:
      path: ""
      type: "editor_tutorials"
    values:
      layout: post
plugins:
  - jekyll-redirect-from
